# Generated by Django 5.2.4 on 2026-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(db_index=True, max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_time_ms", models.PositiveIntegerField()),
                (
                    "request_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "response_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("db_query_count", models.PositiveIntegerField(default=0)),
                ("db_time_ms", models.PositiveIntegerField(default=0)),
                ("concurrent_requests", models.PositiveIntegerField(default=0)),
                ("user_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="performance_endpoin_a0f3a3_idx",
                    ),
                    models.Index(
                        fields=["created_at", "response_time_ms"],
                        name="performance_created_a23955_idx",
                    ),
                    models.Index(
                        fields=["status_code", "created_at"],
                        name="performance_status__9a1cb6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[("api", "API"), ("websocket", "WebSocket")],
                        max_length=20,
                    ),
                ),
                ("endpoint_or_consumer", models.CharField(max_length=255)),
                (
                    "granularity",
                    models.CharField(
                        choices=[("minute", "Minute"), ("hour", "Hour")], max_length=10
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.PositiveIntegerField(default=0)),
                ("p50_ms", models.PositiveIntegerField(default=0)),
                ("p95_ms", models.PositiveIntegerField(default=0)),
                ("p99_ms", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_request_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "avg_response_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["log_type", "endpoint_or_consumer", "window_start"],
                        name="performance_log_typ_9d8f86_idx",
                    ),
                    models.Index(
                        fields=["window_start", "p99_ms"],
                        name="performance_window__2a80c1_idx",
                    ),
                ],
                "unique_together": {
                    ("log_type", "endpoint_or_consumer", "granularity", "window_start")
                },
            },
        ),
        migrations.CreateModel(
            name="SystemResourceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("celery_worker", "Celery Worker"),
                            ("celery_beat", "Celery Beat"),
                            ("redis", "Redis"),
                            ("postgres", "Postgres"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "instance_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cpu_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ram_used_mb", models.PositiveIntegerField()),
                ("ram_total_mb", models.PositiveIntegerField()),
                ("ram_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "disk_used_gb",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "disk_total_gb",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "disk_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "open_file_descriptors",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("active_threads", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "celery_active_tasks",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "celery_queued_tasks",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "celery_reserved_tasks",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "redis_used_memory_mb",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "redis_connected_clients",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "redis_blocked_clients",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "postgres_active_connections",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "postgres_idle_connections",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "postgres_db_size_mb",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["service_type", "service_name", "captured_at"],
                        name="performance_service_ffca7d_idx",
                    ),
                    models.Index(
                        fields=["captured_at", "cpu_percent"],
                        name="performance_capture_17c19f_idx",
                    ),
                    models.Index(
                        fields=["captured_at", "ram_percent"],
                        name="performance_capture_bc97ef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebSocketEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_name", models.CharField(db_index=True, max_length=100)),
                ("connection_id", models.UUIDField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("connect", "Connect"),
                            ("disconnect", "Disconnect"),
                            ("receive", "Receive"),
                            ("send", "Send"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "message_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "connection_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("user_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["consumer_name", "created_at"],
                        name="performance_consume_31229a_idx",
                    ),
                    models.Index(
                        fields=["connection_id", "created_at"],
                        name="performance_connect_38734d_idx",
                    ),
                    models.Index(
                        fields=["created_at", "processing_time_ms"],
                        name="performance_created_f343a2_idx",
                    ),
                ],
            },
        ),
    ]
