# Generated by Django 5.2.4 on 2026-05-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_add_capture_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SlowQueryLog",
        ),
        migrations.RemoveField(
            model_name="apirequestlog",
            name="exception_type",
        ),
        migrations.RemoveField(
            model_name="apirequestlog",
            name="trace_id",
        ),
        migrations.RemoveField(
            model_name="performancesummary",
            name="avg_concurrent_requests",
        ),
        migrations.RemoveField(
            model_name="performancesummary",
            name="avg_db_query_count",
        ),
        migrations.RemoveField(
            model_name="performancesummary",
            name="avg_db_time_ms",
        ),
        migrations.RemoveField(
            model_name="performancesummary",
            name="max_db_query_count",
        ),
        migrations.RemoveField(
            model_name="performancesummary",
            name="p95_db_time_ms",
        ),
        migrations.RemoveField(
            model_name="websocketeventlog",
            name="db_query_count",
        ),
        migrations.RemoveField(
            model_name="websocketeventlog",
            name="db_time_ms",
        ),
        migrations.RemoveField(
            model_name="websocketeventlog",
            name="trace_id",
        ),
    ]
