# Generated by Django 5.2.4 on 2026-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_delete_slowquerylog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequestlog",
            name="exception_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="apirequestlog",
            name="trace_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="performancesummary",
            name="avg_concurrent_requests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancesummary",
            name="avg_db_query_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancesummary",
            name="avg_db_time_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancesummary",
            name="max_db_query_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancesummary",
            name="p95_db_time_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websocketeventlog",
            name="db_query_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websocketeventlog",
            name="db_time_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websocketeventlog",
            name="trace_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="SlowQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sql_hash", models.CharField(db_index=True, max_length=64)),
                ("sql_sample", models.TextField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("endpoint", models.CharField(db_index=True, max_length=255)),
                ("trace_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="performance_endpoin_0bfe36_idx",
                    ),
                    models.Index(
                        fields=["created_at", "duration_ms"],
                        name="performance_created_3a9673_idx",
                    ),
                    models.Index(
                        fields=["sql_hash", "created_at"],
                        name="performance_sql_has_a4dd97_idx",
                    ),
                ],
            },
        ),
    ]
