# Generated by Django 6.0.7 on 2026-07-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_delete_slowquerylog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequestlog",
            name="request_headers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apirequestlog",
            name="response_headers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
