# Generated by Django 6.0.7 on 2026-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0006_apirequestlog_request_headers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequestlog",
            name="request_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apirequestlog",
            name="response_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apirequestlog",
            name="server_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
